import { Event } from '@entities/event/model/types';

export const TEST_EVENT: Event = {
  id: '1',
  title: '팀점심',
  date: '2024-11-03',
  startTime: '12:00',
  endTime: '13:00',
  description: '팀 점심 회의',
  location: '회의실',
  category: '개인',
  repeat: { type: 'none', interval: 0 },
  notificationTime: 10,
};

export const TEST_EVENTS: Event[] = [
  {
    id: '1',
    title: '기존 회의',
    date: '2024-11-15',
    startTime: '09:00',
    endTime: '10:00',
    description: '',
    location: '',
    category: '',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 0,
  },
  {
    id: '2',
    title: '팀 회의',
    date: '2024-11-15',
    startTime: '10:00',
    endTime: '11:00',
    description: '',
    location: '',
    category: '',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 0,
  },
];

export const FILTERED_EVENTS: Event[] = [
  {
    id: '1',
    title: '주간 회의',
    description: '팀 주간 회의',
    location: '회의실 A',
    startTime: '10:00',
    endTime: '11:00',
    date: '2024-01-01',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 10,
  },
  {
    id: '2',
    title: '점심 약속',
    description: '클라이언트와 점심 미팅',
    location: '레스토랑',
    startTime: '12:00',
    endTime: '13:00',
    date: '2024-01-02',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 10,
  },
  {
    id: '3',
    title: '프로젝트 미팅',
    description: '신규 프로젝트 점검',
    location: '회의실 B',
    startTime: '14:00',
    endTime: '15:00',
    date: '2024-01-15',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 10,
  },
  {
    id: '4',
    title: 'SPECIAL EVENT',
    description: '신규 프로젝트 점검',
    location: '회의실 B',
    startTime: '14:00',
    endTime: '15:00',
    date: '2024-01-15',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 10,
  },
];
